### ISSUE TITLE
Support USE statement

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla-rust-driver#109]
The USE <keyspace> statement isn't particularly complicated, but it should be treated in a special way - it should be propagated to all underlying connections for a given CQL session, since it changes their state.

**Comment by avikivity** [comment]
(and to future connections, too - so I think the trick of reusing USE won't work, the driver will have to remember all of them)

**Comment by psarna** [comment]
@avikivity right, the drivers probably remember only the last one. We could also make latency limits a Scylla-specific feature that requires driver support, just like shard awareness does. Maybe the keyword should be changed though,so that existing drivers don't try to remember gibberish as a keyspace name.

**Comment by avikivity** [comment]
Yes. Perhaps @kostja can suggest syntax.

**Comment by kostja** [comment]
In ANSI, current catalog/schema (what is keyspace in scylla), as well as the current authenticated user is property of a session. With connection pooling it is perhaps easiest to creaste an own pool for each session. 
I don't get the question about syntax, AFAIU the ANSI syntax for switching the current schema is
ALTER SESSION SET CURRENT_SCHEMA = <schema name>

See also a relevant MySQL task: 
https://dev.mysql.com/worklog/task/?id=2073

**Comment by avikivity** [comment]
@kostja sorry I was unclear, the issue lacks context. We were discussing overloading USE to set other session properties (beyond the current keyspace), then decided against it because the drivers will remember the last USE statement. So if you issue a sequence like

````
USE my_keyspace
USE session_type = latency sensitive
```

will lose one of the directives.

We need to keep USE for its original use, and add another statement to set session properties. The session properties can include

 - whether the session is throughput oriented or latency oriented
 - session specific timeouts

For a throughput oriented session, we can send keep-alive empty pages in response to slow queries, instead of timing them out.

**Comment by psarna** [comment]
I suppose the discussion should continue on scylladb/scylla github instead of here, so as not to confuse my poor students even further :)  Since this particular issue is only about implementing proper support for the USE statement in the Rust driver. I'll create/find a proper scylla issue tomorrow.
