### ISSUE TITLE
Unhandled source port collisions (Address already in use error)

### ISSUE THREAD

**Issue by cvybhu** [scylladb/scylla-rust-driver#149]
Currently when connecting to a shard we choose a source port number randomly from the range 49,152-65,535 (16,384 possible values). This means that collisions will start happening after ~160 opened connections (due to birthday paradox).

When running tests on a node with multiple shards they start to fail because of these collisions.

The easiest solution would be to make `ConnectionKeeper` detect this error and retry with a different source port.
Currently `ConnectionKeeper` fails on any error.

Alternatively we could start choosing ports linearly?

**Comment by piodul** [comment]
We should definitely detect and retry in the "port in use" error case - no scheme of choosing source ports is immune from collisions, because there is always a risk that another application has a port opened in that range and we accidentally hit it.

IMO, when connecting, we could start from a random port for the desired shard (as we do now), and increase the port by num_shards every time connecting fails with "port in use" error. When we reach the end of the range, we wrap around to the beginning. When we reach the port that we began with, we should return an error indicating that there are no ports available (in the future, we could fall back to the non-shard-aware port here, but we don't support it yet).

@psarna WDYT?

**Comment by psarna** [comment]
Makes sense
