### ISSUE TITLE
Let the driver manage prepared statements

### ISSUE THREAD

**Issue by dtzxporter** [scylladb/scylla-rust-driver#151]
Other cassandra drivers (Notably Go/Node.js's) support an internal cache for prepared statements. Would it make sense to do the same thing here to transparently cache them the first time without leaving that up to the binary?

**Comment by psarna** [comment]
Yes, definitely makes sense. Just to confirm - you're suggesting that the driver could decide on its own that a user's query (submitted with `session.query(...)` can be internally cached and prepared, in order to make its next executions faster, right?

**Comment by dtzxporter** [comment]
Yep! Or even forced by a parameter if necessary.

**Comment by Jasperav** [comment]
I think it's better to make it a separate method (else the user is forced to use prepared statements). There is additional logic involving caching prepared statements (resending prepared statement to the DB if the prepared statement is expired, this happend in CDRS: https://github.com/AlexPikalov/cdrs/pull/348), this is maybe unnecessary if the query is only executed once.

**Comment by psarna** [comment]
Yes, we should avoid polluting the server-side cache unnecessarily with statements executed once, so a separate method would be a good compromise.

**Comment by psarna** [comment]
Or perhaps as a session configuration (e.g. `let session = SessionBuilder::new().with_auto_prepare().build()`)

**Comment by Jasperav** [comment]
When fixing this issue, please also keep https://github.com/Metaswitch/cassandra-rs/issues/110 in mind. @psarna can you verify ScyllaDB has the same behaviour as Cassandra, regarding unable to identify schema changes (and thus keeping an invalid query in cache)?

**Comment by psarna** [comment]
@Jasperav ScyllaDB always flushes prepared statement caches on schema changes to avoid incorrect query execution.

**Comment by piodul** [comment]
@psarna, the problem described in the issue is related to caching prepared statement metadata (types of returned columns, how to calculate the token, etc.). The problem comes from the fact that Cassandra doesn't include information about the table schema when calculating prepared statement ID. The following situation can happen:

- Clients A and B both use the same prepared statement of form `SELECT * FROM tbl`,
- Schema of `tbl` changes, prepared statements are invalidated,
- Client A tries to execute the statement, sees that it is invalid and reprepares it, fetching the new metadata and caching it. Cassandra will return _the same ID_ for that statement, probably because its text didn't change.
- Client B executes the statement - which succeeds because it was re-prepared by client A and has the same ID. It won't notice that the statement was invalidated at all, and it won't ever update the metadata.

C* fixes this in protocol v5 by adding [`result_metadata_id`](https://github.com/apache/cassandra/blob/5ed5e84613ef0e9664a774493db7d2604e3596e0/doc/native_protocol_v5.spec#L575-L578).

I don't think this problem affects the driver _at the moment_, because we don't use cached metadata for parsing rows, we always request metadata in the response when sending a statement and use it to parse the result. We also don't expose prepared statement metadata in the public interface yet. However, in the future we probably will want to use prepared statement metadata for parsing results, so it's worth keeping this issue in mind.

**Comment by psarna** [comment]
Ah, ok, makes sense. And that's right, prepared statement id happens to simply be an md5 sum of the query string.

**Comment by Jasperav** [comment]
@psarna Is this still on the roadmap?

**Comment by Jasperav** [comment]
What work needs to be done for this issue? I guess a simple private property HashMap<StringQuery, PreparedStatement> in the session would work in combination with a prepared_cached method, or is it more complex?

**Comment by psarna** [comment]
Pretty much that - although we should also limit the number of entries in the cache, so that it doesn't grow indefinitely. And then, the query path should be extended to optionally query the map of prepared statements before sending anything to Scylla.

**Comment by piodul** [comment]
It would also be nice if, in case the user wants to prepare the same statement from multiple places in the code at the same time, the driver would only send one PREPARE message per host/shard. However, IMO this can be left as a further improvement.

**Comment by Jasperav** [comment]
https://github.com/jeromefroe/lru-rs can be used. When the key isn't present, compute it and store it in the cache. When we want to make sure this doesn't happen twice when it happens at around the exact same time, a tokio mutex must be added to the session which makes things a lot slower and more complicated. I guess it would be if this step will be skipped for now, like @piodul mentions. @psarna you think that is a good library?
