### ISSUE TITLE
Expose a type that represents Unset (Value with -2 len)

### ISSUE THREAD

**Issue by dtzxporter** [scylladb/scylla-rust-driver#159]
Currently, we only support Option<T> -> None -> -1 (Null) but inserting null is the same as inserting a tombstone as far as I am aware and it's better to do unset in the event the value is not set (undefined).

node has support for automatically handling unset as undefined.

We could expose a type that is identical to Option but serializes to 0 length to support unset, or add a configuration option to make Option<T> use unset instead of null.

Please let me know how you'd like to proceed with this task.

**Comment by psarna** [comment]
Right, we need to support `UNSET`. Perhaps instead of Option we should simply introduce our own enum type which supports all 3 combinations, like:
```rust
enum Value {
    Regular(i32),
    Null,
    Unset
}
```

**Comment by psarna** [comment]
@piodul opinions?

**Comment by piodul** [comment]
> We could expose a type that is identical to Option but serializes to 0 length to support unset, or add a configuration option to make Option use unset instead of null.

@dtzxporter  Just a small clarification: the CQL protocol uses [length == -2](https://github.com/scylladb/scylla-tools-java/blob/5c8de45dc9646c89664d594b388f27bb8660ce12/doc/native_protocol_v4.spec#L212-L213) to represent an unset value. 0-length value is something different - e.g. for `text` it represents an empty string, which is distinct from NULL, and it not an unset value.

> @piodul opinions?

@psarna I'm worried that the enum which you proposed would not work well with the main interface for sending queries:

```rust
session
    .query("INSERT INTO ks.t (a, b, c) VALUES (?, ?, ?)", (3, Value::Unset, "def"))
    .await?;
```

The enum will probably have to be generic so it can hold any valid, concrete type, eg. `i32`, `String` or `CQLType` which is our catch-all for all types:

```rust
use scylla::value::Value;

// Changed the name because we already have "Value" as a trait
enum Maybe<V: Value> {
    Unset,
    Null,
    Value(V),
}
```

Both of these things will probably cause type inference errors because Rust won't be able to deduce the `V` parameter for `Value::Unset` in the first snippet.

We can solve this by adding a unit struct `Unset` which will always serialize itself to empty value with length '-2`:

```rust
struct Unset;
```

As for the `Value`/`Maybe` struct, we can include it for completeness' sake. Another thing to consider is if it should have three variants - maybe we should drop the `Null`?

```rust
enum MaybeUnset<V: Value> {
    Unset,
    Set(V),
}
```

This offers greater elasticity - somebody maybe would like to have a choice between unset/set value, but not consider nulls. On the other hand, if somebody wants to have three options, they can use `MaybeUnset<Option<V>>`. This uses more space than a three-valued enum (additional 4 bytes for the enum discriminant), but I doubt it will be commonly used.

**Comment by psarna** [comment]
`struct Unset` sounds neat.
