### ISSUE TITLE
Tests fail on Windows

### ISSUE THREAD

**Issue by cvybhu** [scylladb/scylla-rust-driver#205]
The test `transport::connectinon_keeper::tests::many_connections` fails on Windows 10.
This test opens many connections from many different source ports.
The test fails with `PermissionDenied` so maybe we are trying to use some ports which are forbidden on Windows?

Github Actions support running Windows, we should add a windows workflow which runs `cargo test` to avoid such surprises in the future.

**Comment by psarna** [comment]
Yup, makes sense. This particular test doesn't seem crucial so we might just mark it as ignored on Windows, but we should have Windows-based CI anyway.

**Comment by cvybhu** [comment]
The fact that this test fails means that the driver will sometimes randomly fail to connect to some shard, I'm not sure if we can just ignore it. 
After 8 seconds it will reconnect and probably succeed, but if there is for example only 1 shard the driver might not work for the first 8 seconds.

**Comment by psarna** [comment]
True. We can spend some time on a short investigation - if it's a matter of reducing the range of ports on Windows to some known value to make the tests pass, I'm definitely fine with that. But if it's something more complex and not properly documented by Microsoft, I'm also fine with ignoring this test case temporarily.

**Comment by piodul** [comment]
I did some investigation and it turns out that it is possible for processes with administrative privileges to reserve some ports so that others cannot bind to them. This includes, for example, Docker for Windows which some of us probably use to run Scylla on Windows in order to run scylla-rust-driver's tests - see this issue: https://github.com/docker/for-win/issues/3171.

I managed to find a WinAPI function - [CreatePersistentTcpPortReservation function](https://docs.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-createpersistenttcpportreservation) - which creates such reservations. Using the snippet from the doc page, I reproduced the "permission denied" error by reserving a port range and trying to bind a socket to a port from the reserved range from an unprivileged process.

I didn't find any information which would specify what ranges of ports can be reserved and which cannot, so I don't think we can adjust the range to completely avoid reserved ports. I think proceeding to the next port when we encounter a reserved port is the most sensible thing we can do.
