### ISSUE TITLE
Improve ergonomics of handling response data

### ISSUE THREAD

**Issue by piodul** [scylladb/scylla-rust-driver#214]
Currently, our API is a little cumbersome when it comes to processing data from query response. An example from our tests:

```rust
let (read_timeuuid,): (Uuid,) = session
    .query("SELECT val from ks.timeuuid_tests", &[]) // 1. create a future which will execute the query
    .await                                           // 2. await the future
    .unwrap()                                        // 3. handle possible error (from db, or transport error)
    .rows                                            // 4. QueryResult has multiple fields, "rows" has the data
    .unwrap()                                        // 5. "rows" is an Option<Vec<Row>>, need to unwrap it
    .into_typed::<(Uuid,)>()                         // 6. turn it into TypedRowIter
    .next()                                          // 7. get the first value from the iterator (which is an Option)
    .unwrap()                                        // 8. unwrap the option
    .unwrap();                                       // 9. TypedRowIter parses rows on the fly, so it returns results - handle it
```

This is way too many steps for a simple operation like fetching one row - not to mention that non-testing code might wish to properly handle the edge cases without resorting to unwraps.

We should think of some common use cases and add helper methods which will make it easier to handle them. The ones I can think of are:

- Fetching single row,
- Fetching multiple rows,
- Executing an operation which does not expect any rows (e.g. insert)

**Comment by cvybhu** [comment]
I opened a PR with basic ergonomics improvements: #222

I think it would be possible to remove one more line, but it would require some major changes.

We could add a special query function in `Session` which takes the type as wich rows should be parsed and returns `QueryResult` where all rows are already of this type. This would allow to put the parsing `Result` in `Result` of this function instead of checking two results.

Something like:
```rust
pub struct QueryResult<RowT> {
    /// Rows returned by the database
    pub rows: Vec<RowT>,
}

pub async fn query_typed<RowT: FromRow>(
    &self,
    query: impl Into<Query>,
    values: impl ValueList,
) -> Result<QueryResult<RowT>, QueryError> {
    unimplemented!();
}
```

Which could then be used like this:
```rust
let (read_timeuuid,): (Uuid,) = session
    .query_typed::<(Uuid,)>("SELECT val from ks.timeuuid_tests", &[]) // 1. create a future which will execute the query
    .await                                         // 2. await the future
    .unwrap()                                      // 3. handle possible error (from db, transport, row parse)
    .first_row()                                   // 4. Get first row as the given type
    .unwrap();                                     // 5. Unwrap Option which is None if rows are empty
```

This would require doubling all `Session` queries and major changes in `Session` and `Connection`.
I'm not sure if it's worth it - we gain a single line, but have to double apis and introduce another method of doing the same thing.
I will look around and think about it.
