### ISSUE TITLE
Session Clone

### ISSUE THREAD

**Issue by sankar-boro** [scylladb/scylla-rust-driver#216]
Can we implement Clone on Session? I was trying to use scylla-rust-driver on actix-web.

**Comment by Jasperav** [comment]
Why not wrap it in an Arc?

**Comment by cortopy** [comment]
Arc would have the risk of bottlenecks since there is only one connection established. It also may be more expensive and less efficient than other patterns

For example, in other database drivers, the idea of cloning is not just so that you can pass a connection around. It's actually a way of having a pool of connections, and when the client is cloned, one of those connections is shared. The driver manages internally the number of connections, pooling, re-connections, etc.

[r2d2 is a nice high-level wrapper](https://crates.io/search?q=r2d2) for different database drivers. If this driver implemented [ManageConnection](https://docs.rs/r2d2/0.8.9/r2d2/trait.ManageConnection.html) it would be great

**Comment by Jasperav** [comment]
@cortopy Good point, I thought this crate actually had connection pooling, but I think I am wrong. Connection pooling would be great. @psarna @piodul is this on the roadmap?

**Comment by psarna** [comment]
It is. Our main goal was to ensure that we support a connection per shard for a Scylla cluster, which was already achieved, but we should also introduce a way of managing multiple connections to the same node regardless if it supports shards.

And as for cloning, it still makes sense to implement it as a way of creating a new session with identical config. It shouldn't be particularly hard.

**Comment by kbr-** [comment]
AFAIK in all other drivers it is recommended to use a single session which does connection pooling underneath.

This driver's sessions also manage a pool of connections. At least one connection per shard. It should be possible to define that you want to have N connections per shard (although 1 is usually enough); this is what the Java driver allows, for example; if it's not possible yet, the feature should be implemented.

I'm not sure if creating multiple sessions is a good idea - it would create multiple connection pools. So, for example, if you concurrently perform two requests on two different sessions, the requests would go on separate connections, while they could potentially go on the same connection (without any loss of efficiency because connections support parallel requests); but you're wasting resources by establishing more connections than you need.

For now, I think we should recommend going with Arc.

**Comment by kbr-** [comment]
> AFAIK in all other drivers it is recommended to use a single session which does connection pooling underneath.

The only exception is the Python driver which requires using multiple processes for achieving concurrency (due to the GIL), in which case you use a single session per process.

**Comment by Jasperav** [comment]
> For now, I think we should recommend going with Arc.

Sure? If you clone the Arc a lot and use it in different places, every query needs to wait on previous query to complete. I think the connection pooling should be build into the session for optimal performance.

**Comment by kbr-** [comment]
> Sure? If you clone the Arc a lot and use it in different places, every query needs to wait on previous query to complete.

This shouldn't happen. Sessions should handle concurrent requests.
First, the two queries may go on different connections.
Second, even if they go on the same connection, Scylla's connections allow pipelining of requests.

Did you confirm this experimentally?

> I think the connection pooling should be build into the session for optimal performance.

I'm saying that it already is. This example shows how to perform concurrent requests on a single session: https://github.com/scylladb/scylla-rust-driver/blob/main/examples/parallel-prepared.rs

**Comment by kbr-** [comment]
> @psarna @piodul is this on the roadmap?

> It is. (...)

Maybe @psarna 's answer was a bit confusing.
We **already have** connection pooling. A single session stores a single connection per shard per node. So if there are 3 nodes with 3 shards on each, the session will store a pool 9 connections (plus one "control" connection for refreshing topology info etc.)

The plan is to improve it, by supporting multiple connections per shard.
(which, by the way, you should never need.)

**Comment by Alkeryn** [comment]
sorry for the necrobump, but any news on this ?
we still can't clone() the session and using an arc has big disadvantage.

is session thread safe ? in which case there are many ways we could share it using unsafe.

**Comment by psarna** [comment]
Session is not thread safe and is a quite heavy object - it contains a control connection + the pool of regular connections, topology information, and so on. In case you need multiple sessions, e.g. one per fiber, the most reasonable way to achieve it now is to simply create multiple sessions using the SessionBuilder interface. You just create a builder once, and then call `build()` multiple times, the function is adapted to such a use case. `Session` could implement `clone()` in a similar fashion if it kept its `SessionConfig` instance, but it currently doesn't, because it doesn't need it, and `SessionConfig` is stored in `SessionBuilder` anyway.

Example code for creating multiple sessions with a single builder:
```rust
    let builder = SessionBuilder::new()
        .known_node("127.0.0.1:9042")
        .user("cassandra", "cassandra");

    let sessions: Vec<Session> = futures::future::join_all((0..16).map(|_| builder.build()))
        .await
        .into_iter()
        .map(|r| r.unwrap())
        .collect();
```

**Comment by kbr-** [comment]
> using an arc has big disadvantage.

Could you tell me what your problems are with using an Arc?

**Comment by Alkeryn** [comment]
@kbr- in the case of many simultaneous request wouldn't it slow things down since Arc needs be atomic ?

**Comment by kbr-** [comment]
Ok, so the heart of the matter is in the fact that `query` takes an **immutable reference** to Session:
```rust
    pub async fn query(
        &self,
        query: impl Into<Query>,
        values: impl ValueList,
    ) -> Result<QueryResult, QueryError> {
```

hence you can query from different tasks safely.
AFAIU if it was a mutable reference, Rust wouldn't compile this code at all.

**Comment by kbr-** [comment]
Anyway here's a simple set of guidelines:
1. Use a single `Session` unless you have a very very good reason not to (let's say you have two different types of workloads so you want to configure sessions separately - then you want two sessions)
2. Pass the `Session` to different fibers using Arcs.
3. Establish your fibers at the beginning of the program, passing your Arcs into those fibers. Then you only perform the atomic operations once at the beginning, and your fibers will simply reuse the existing Arcs.

**Comment by Alkeryn** [comment]
@kbr- thanks for all the replies and the time you took to reply, that was very helpful ! 😀
let's say i use actix web, would you put the prepared statements in an array behind an arc or something like that ?
or should i rather use cachingsession ?

**Comment by psarna** [comment]
@Alkeryn try CachingSession (specifically, an `Arc<CachingSession>` passed to different fibers as @kbr- recommends), it should work out of the box for your use case and hide the implementation details for preparing all the statements.

**Comment by Alkeryn** [comment]
@psarna thanks ! :)

**Comment by louiscb** [comment]
I have a general question about the usage of the Session. In general should one instance of an application just have one Session? Or should we spawn several. Above a few people mention that the driver will internally handle pooling. So I assume queries to execute on the same session instance will be handled async and not blocked?

**Comment by kbr-scylla** [comment]
@louiscb

> In general should one instance of an application just have one Session?

Already answered above:
https://github.com/scylladb/scylla-rust-driver/issues/216#issuecomment-1184504520

@piodul maybe we need to improve documentation for `Session`?

**Comment by louiscb** [comment]
@kbr-scylla Thanks. I would suggest adding a sentence e.g "Use a single Session unless you have a very very good reason not to" to this page: https://rust-driver.docs.scylladb.com/stable/connecting/connecting.html

**Comment by Lorak-mmk** [comment]
Is there a reason to keep this open? Questions about session handling were answered (this is valid and current recommendation: https://github.com/scylladb/scylla-rust-driver/issues/216#issuecomment-1184504520 ), so I guess there is nothing more to do.

I saw that there was an idea to implement `Clone` on `Session` and it would estabilish a new `Session`.
This approach has a problem: creating `Session` is an async operation (see `GenericSessionBuilder::build`), so in order to perform it in `clone` it would need Tokio's `block_on`, which in this case is imo an antipattern and will cause problems down the line.
There aren't many (any?) good reasons to create multiple Sessions with the same config anyway - so if someone wants to do that anyway, requring to do this explicitly by calling `build` multiple times seems like the corrent API choice to me.

**Comment by piodul** [comment]
> Is there a reason to keep this open? Questions about session handling were answered (this is valid and current recommendation: [#216 (comment)](https://github.com/scylladb/scylla-rust-driver/issues/216#issuecomment-1184504520) ), so I guess there is nothing more to do.

We should put those recommendations into our documentation so that people find their answers there rather than here in this issue.

We should also give some rationale behind the recommendations: shortly explain that the Session maintains a pool of connections and that each connection is capable of handling multiple requests asynchronously, so it's best to let the session manage connections by itself (and also choose connections for requests - remember that we have token-aware load balancing).

> I saw that there was an idea to implement `Clone` on `Session` and it would estabilish a new `Session`. This approach has a problem: creating `Session` is an async operation (see `GenericSessionBuilder::build`), so in order to perform it in `clone` it would need Tokio's `block_on`, which in this case is imo an antipattern and will cause problems down the line. There aren't many (any?) good reasons to create multiple Sessions with the same config anyway - so if someone wants to do that anyway, requring to do this explicitly by calling `build` multiple times seems like the corrent API choice to me.

It makes sense to me to forbid cloning and make creating new sessions explicit. However - again - we should put this into the documentation. For example, bb8 - a connection pooling crate, a successor to the rd2d mentioned in this discussion - has the `Pool` struct which [_is_ cloneable](https://docs.rs/bb8/latest/bb8/#example) and implements shared-pointer semantics (i.e. it behaves as `Arc<Session>` would behave in our case, [it literally is implemented as an `Arc`](https://docs.rs/bb8/latest/src/bb8/inner.rs.html#16)). I think that the expectation that our crate behaves the same was the source of confusion, so we should clearly explain that we behave differently.
