### ISSUE TITLE
Feature request: table and keyspace macros and creation

### ISSUE THREAD

**Issue by cortopy** [scylladb/scylla-rust-driver#252]
I'm not sure if this project is accepting feature requests, but after first use of the driver I'm missing some ergonomics for tables and keyspaces.

I personally love [Diesel macros](https://docs.rs/diesel/1.4.7/diesel/macro.table.html) for declaring a schema and getting methods generated automatically

Also, it would be great to be able to manage schemas and migrations with code [like Diesel](https://docs.rs/diesel_migrations/1.4.0/diesel_migrations/), although this is probably a separate issue

**Comment by psarna** [comment]
We do accept feature requests, but due to the open-source nature of this driver, the request is likely to wait until a contribution :) Macros for defining schemas are a great idea, thanks for pointing out a reference implementation.

**Comment by Jasperav** [comment]
@cortopy I made such code for Cassandra/ScyllaDB in https://github.com/Jasperav/cdrs_orm, but it doesn't support this crate yet since https://github.com/scylladb/scylla-rust-driver/issues/231 and https://github.com/scylladb/scylla-rust-driver/issues/216 (connection pooling) are not implemented yet. The ORM can generate Rust structs from tables and compile time checked queries :)

**Comment by cortopy** [comment]
@Jasperav that's looking great!!! thanks for that

**Comment by wprzytula** [comment]
The requested functionality belongs to ORM domain. It should be implemented on top of the driver, not in the driver itself.
