### ISSUE TITLE
Use paged queries for fetching topology information

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla-rust-driver#298]
As of now, we fetch topology information by issuing unpaged queries to the database. It's usually fine, since topology info is not that big, but the output from `system.peers` can actually grow big for large clusters, and `system_schema.keyspaces` can also contain thousands of rows if somebody creates thousands of keyspaces. In order to avoid stalls and large allocations on the nodes, we should instead rewrite the queries to use regular paging.

Ref:
https://github.com/scylladb/scylla-rust-driver/blob/3c2f4e3805650b223740fd1a710910945f0ff7ae/scylla/src/transport/topology.rs#L197-L284

**Comment by cvybhu** [comment]
We should have some way to query all pages in a simple way
Something like `session.query_all()` that would do a paged query and collect all the results

It is the most common use case, it's the only type of queries that we do in the driver.

Maybe we should even change `Session::query` so that it will query all pages? It's really unintuitive that the default query option gets only a single page of results.

`Connection::query` could also query all pages instead of only one

**Comment by psarna** [comment]
> We should have some way to query all pages in a simple way
> Something like `session.query_all()` that would do a paged query and collect all the results

Yup.

> It is the most common use case, it's the only type of queries that we do in the driver.
> 

Yes, I agree, we should use it everywhere internally.

> Maybe we should even change `Session::query` so that it will query all pages? It's really unintuitive that the default query option gets only a single page of results.

Nooope. While we heavily discourage unpaged queries, they're legal in CQL, so according to Hyrum's law somebody's architecture already relies on unpaged queries and we shouldn't break existing use cases (and paging internally in the driver adds to latency due to more round trips). What we could do is logging a warning when somebody issues a huge unpaged query.

> 
> `Connection::query` could also query all pages instead of only one
