### ISSUE TITLE
Invalid message: Error parsing message: Could not serialize frame: unknown consistency: 9

### ISSUE THREAD

**Issue by rh2048** [scylladb/scylla-rust-driver#369]
I seem to be receiving the following error sporadically:

```
Invalid message: Error parsing message: Could not serialize frame: unknown consistency: 9
```

My session configuration is pretty straightforward:

```rust
let mut session_builder = scylla::SessionBuilder::new();
session_builder = session_builder.use_keyspace(&config.keyspace, false);
// ...call `session_builder.known_node`...
// ...call `session_builder.user`
let session = session_builder.build().await?;
```

Running a 3 node cluster with all keyspaces configured with `replication = {'class': 'NetworkTopologyStrategy', 'replication_factor': 3}`.

Unable to reproduce this issue consistently other than when running a high number of queries in parallel.

Version:

```
[dependencies.scylla]
git = "https://github.com/cvybhu/scylla-rust-driver.git"
rev = "19c5df8205614c32f7c87279b3ce9c9a7e83d70e"  # See https://git.io/Jy6EW
features = ["ssl"]
```

**Comment by penberg** [comment]
I think this got broken by bff127f0511fac59f214f51b63ef3808a8d89c02 which split consistency and serial consistency into separate enums. @psarna I guess `read_consistency()` needs to know about serial consistency too?

**Comment by psarna** [comment]
Indeed - a whole class of errors keeps consistency information (e.g. https://github.com/scylladb/scylla-rust-driver/blob/51e088291b174cb2af6e6ed07cbbd48dfa6c5907/scylla/src/transport/errors.rs#L93-L100 )

and we need to make these errors work with SerialConsistency too, since it got broken by bff127f. I suppose a proper solution would be to have these errors store an enum which allows either Consistency or SerialConsistency values, not just Consistency.
