### ISSUE TITLE
Support `unsigned` versions of integers.

### ISSUE THREAD

**Issue by dtzxporter** [scylladb/scylla-rust-driver#409]
Unsigned versions can be automatically mapped to the `signed` versions that database uses.

**Comment by psarna** [comment]
Lossy - definitely not. A runtime bound check should be performed

**Comment by gsson** [comment]
Since it just bit me, for varints columns I think it should Just Work

**Comment by Lorak-mmk** [comment]
I think that this idea may backfire on us later. Lack of unsigned types in Scylla / C* is of course an issue for some application developers because it increases complexity (as the developer now needs to validate data and deal with errors).
This complexity is however inherent to developing with Scylla / C* (as long as they don't have unsigned types) and trying to hide this complexity may cause a perfectly working application to suddenly start throwing errors after long time.

New deserialization framework will probably allow to downcast error to specific implementation and check what exactly went wrong - but doing this will be much more difficult that creating 2 structures (first with signed types, to interact with DB, second with unsigned types, to use in rest of the application) and handling conversion errors.

for those reasons I think it's better to make users aware of this complexity and deal with it explicitly - it will result in more robust, less error-prone applications.

**Comment by JonahPlusPlus** [comment]
Instead of implementing `SerializeCql` and `FromCqlVal` for `u*` types, this crate could provide wrapper types for handling different serialization patterns.

There are 4 different approaches:
- `as`: Just convert the unsigned to signed and back. (Could be a wrapper like `SignedU*`)
- `MappedU*`: e.g. `MappedU32(u32)` would map the range of an `u32` to the range of an `i32`. (So, `u32::MIN..u32::MAX -> i32::MIN..i32::MAX`)
- `BlobU*`: e.g. `BlobU32(u32)` would convert the `u32` to `[u8; 4]` and back. (Also supports `u128`)
- `BigInt`: Store the signed number as a `BigInt`. (Could be a wrapper like `VarU*`)

I'm using `MappedU*` and `BlobU*` in my project.
