### ISSUE TITLE
The same code using 0.4 will make an error

### ISSUE THREAD

**Issue by dragon-D** [scylladb/scylla-rust-driver#437]
```
use anyhow::Result;
use scylla::{SessionBuilder, Session};

#[tokio::main]
async fn main() -> Result<()> {
    let uri = std::env::var("SCYLLA_URI").unwrap_or_else(|_| "127.0.0.1:9042".to_string());
    println!("Connecting to {} with cassandra superuser ...", uri);
    let session: Session = SessionBuilder::new()
        .known_node(uri)
        .user("cassandra", "cassandra")
        .build()
        .await
        .unwrap();
    
    println!("Ok.");
    Ok(())
}
```
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidMessage("type map<text, frozen<map<text, text>>> is not implemented")', src/bin/d.rs:15:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

cargo.toml
```
scylla = "0.4"
anyhow = "1.0.33"
```

But if you use 0.3 it will be successful
```
scylla = "0.3"
anyhow = "1.0.33"
```

**Comment by piodul** [comment]
It looks like a bug in the logic which parses cql type descriptions from the system tables. Because there are two commas, the parser incorrectly tries to interpret it as a `map<>` with three arguments between the angled brackets and fails because maps are supposed to have only two.

I'll improve the parser. In the meantime, if you would like to use version "0.4" you can try setting `.fetch_schema_metadata(false)` in the session builder. The driver won't automatically fetch schema information and it won't be available in ClusterData, but it should prevent the faulty logic from being triggered.

**Comment by dragon-D** [comment]
> It looks like a bug in the logic which parses cql type descriptions from the system tables. Because there are two commas, the parser incorrectly tries to interpret it as a `map<>` with three arguments between the angled brackets and fails because maps are supposed to have only two.
> 
> I'll improve the parser. In the meantime, if you would like to use version "0.4" you can try setting `.fetch_schema_metadata(false)` in the session builder. The driver won't automatically fetch schema information and it won't be available in ClusterData, but it should prevent the faulty logic from being triggered.

Using` .fetch_schema_metadata(false)` is normal, but I'm not sure if this will have a big impact. I still use version 0.3 first. The next version will be updated if improved.
my scylladb version
```
Scylla version 4.1.11-0.20210105.b0f656302cf
```

**Comment by psarna** [comment]
Good catch. More importantly, such topology fetching failures shouldn't be fatal
