### ISSUE TITLE
Token aware load balancing for batches

### ISSUE THREAD

**Issue by wyfo** [scylladb/scylla-rust-driver#448]
Currently, batches don't support token aware load balancing. However, there could be situations where batches statement are guaranteed to be processed by the same nodes. Enabling token aware load balancing would then improve performance. 

A possible implementation could be to add an additional configuration method, for example `set_compute_token`, and when the flag is set, the token of the batch's first prepared statement is computed to to be used in load balancing policy.

Any opinion about it? I'm volunteer to make the PR.

**Comment by psarna** [comment]
Oh, I thought we already speculatively do that (take the first prepared statement if available and use its token). I think we should even consider doing that unconditionally, since it's good practice to only batch statements within a single partition - in which case the user will be rewarded for their good practice with token awareness for free. Then we don't even need any `set_compute_token`, and the only downside is that batch statements with mixed partitions go to the node which owns the first statement - which is still a good idea, at least part of the batch application will be local.

Contributions welcome! I'll take liberty to assign you to this one, so everyone knows it's taken. Thanks!

**Comment by Ten0** [comment]
> we already speculatively do that

> we should even consider doing that unconditionally

As a new user, I don't understand how speculative isn't unconditional. Could you elaborate?

Thanks,

**Comment by Ten0** [comment]
So just to be sure I understand correctly, this is not currently implemented but is the plan?

**Comment by wyfo** [comment]
> So just to be sure I understand correctly, this is not currently implemented but is the plan?

Indeed, looking in the [code](https://github.com/scylladb/scylla-rust-driver/blob/main/scylla/src/transport/session.rs#L829), it's not implemented.
I had planned to do it but I also had a small accident and I'm now a little bit less productive with a cast on my wrist ...
So I think I should unassign me for now, until I recover.

**Comment by Ten0** [comment]
[This documentation](https://www.scylladb.com/2019/03/27/best-practices-for-scylla-applications/) seems to say that ideal performance would be attained by grouping together queries that end up in the same partition.

However it looks like since:
https://github.com/scylladb/scylla-rust-driver/blob/71889a037adf7cc1246f09262b63c0a5077346d3/scylla/src/transport/session.rs#L1318
is not public (https://github.com/scylladb/scylla-rust-driver/issues/468)
that may actually be impossible right now.

It looks then like as part of implementing this feature, this should also be made public.

**Comment by cvybhu** [comment]
Reopening because of #569
