### ISSUE TITLE
Add address translation capability

### ISSUE THREAD

**Issue by wprzytula** [scylladb/scylla-rust-driver#470]
While present in some other Scylla drivers, address translation is still missing in Rust driver. Consider the following scenario: the cluster nodes are hidden behind some NAT, and therefore the peer addresses fetched by the driver from the cluster would be invalid. To mitigate this issue, one should be able to set up some (probably static) address translation that would assign valid public IP addresses to the nodes, by mapping the received private addresses to the provided public ones.

**Comment by cvybhu** [comment]
The `system.peers` table has a column called `preferred_ip`.
Maybe we should use it instead of `peer` to get node ips.
Then in case of a NATted cluster the admin would set `preferred_ip` to the outside IP and everything would work out of the box.
(??? I'm not sure if that's how it's supposed to work)
```
cqlsh> select * from system.peers;

 peer | data_center | host_id | preferred_ip | rack | release_version | rpc_address | schema_version | supported_features | tokens
------+-------------+---------+--------------+------+-----------------+-------------+----------------+--------------------+--------
```

Address translation could still be useful for more convoluted setups though.
