### ISSUE TITLE
Add LatencyTracker to Session

### ISSUE THREAD

**Issue by wprzytula** [scylladb/scylla-rust-driver#515]
### Motivation
Required e.g. by #505, it would enable updates of all entities that depend on latencies, including `LatencyAwarePolicy`.
 
### Proposed solution
We could create a struct with at least minimum data required for latency tracking: 
```
struct LatencyInfo {
    node: Arc<Node>,
    latency: Duration,
}
```
And then embed a `tokio::sync::broadcast` in `Session`:
```
pub struct Session {
    ...
    latency_tracker: tokio::sync::broadcast::Sender<LatencyInfo>,
}
```
...enable subscribing for it:
```
impl Session {
    ...
    pub fn subscribe_for_latency_tracking(&self) -> tokio::sync::broadcast::Receiver<LatencyInfo> {
        self.latency_tracker.subscribe()
    }
}
```
... and then the latency tracking info would be broadcast from here:
`session.rs:1211:execute_query()`:
```
last_error = match query_result {
  Ok(response) => {
      trace!(parent: &span, "Query succeeded");
      let elapsed = query_start.elapsed();
      self.latency_tracker.send(LatencyInfo{
          node,
          latency: elapsed,
      });
      let _ = self
          .metrics
          .log_query_latency(elapsed.as_millis() as u64);
      return Some(Ok(response));
  }
  ...
};
```

The `LatencyAwarePolicy` would be created using the subscribed `broadcast::Receiver` as an argument.

What do you think about such a solution?
@psarna @piodul @cvybhu

**Comment by psarna** [comment]
How about keeping an (optional) latency tracker within each Node instance? We keep a very limited number of these in memory (since clusters tend to have only a few nodes), and then we won't need any mechanism for broadcasting and subscribing, we could just update the latencies in-place, we have access to `node` in the code snippet you quoted.

**Comment by wprzytula** [comment]
> How about keeping an (optional) latency tracker within each Node instance? We keep a very limited number of these in memory (since clusters tend to have only a few nodes), and then we won't need any mechanism for broadcasting and subscribing, we could just update the latencies in-place, we have access to `node` in the code snippet you quoted.

What do you mean by a "latency tracker within each Node instance"? The `LatencyAwarePolicy` requires to be notified on each query completion in order to update internal statistics, and if we just store the last latency info within `Node`, it won't be able to trigger the policy update accordingly - that's why I would stick to a broadcast. 
Moreover, we would probably prefer to give the user ability to implement arbitrary logic based on subscribed latency tracking.

**Comment by wprzytula** [comment]
@psarna Let's resume the discussion, as I'm back working on this issue.

**Comment by wprzytula** [comment]
@piodul @cvybhu I would appreciate your opinions too.

**Comment by psarna** [comment]
I was sure I posted a response a few days ago, but maybe I didn't hit the Comment button... so let me start over:

Notifying LatencyAwarePolicy is one way, but LatencyAwarePolicy could also ask nodes for their fresh latency information right before making a decision. Then, nodes update their latency info locally when taking part in query processing, and the information is only gathered once needed - i.e. when LatencyAwarePolicy needs to make a decision. I think that this way may make sense, because it delays aggregating computation results until they're needed, and avoids keeping another bunch of atomically refcounted pointers to Node instances. Let's assume we have a token-aware latency-aware policy. Token awareness would reduce the candidates to 3 nodes, and out of these 3 nodes, the latency-aware policy will choose a subset with predicted best latency by examining the nodes' latency information right before making the choice.

**Comment by cvybhu** [comment]
I'm not sure if we can just take the latencies of user queries and use them for detecting local DCs and stuff like that.
Some queries might take a long time because of the query itself, not the network latency.

Maybe we could spawn a latency tracker worker for each node, which would perform a simple query every 60s. This could even be a query that fails to parse, just something to ping the database.
Actually doesn't the code for keeping connections alive do something like this?

Then each node would have some atomic float representing the latency which could be used by latency aware policies.

I agree that the `broadcast` approach looks overcomplicated, does the policy really need to know how each query went to make reasonable choices? Couldn't it just be provided the latency by a third party?

**Comment by psarna** [comment]
@wprzytula could you do a small r&d research and look how it's implemented in Java, and perhaps gocql? I generally agree that latency depends heavily on the query itself, but on the other hand workloads are usually rather homogenous wrt. query type. a 60s ping may be counterproductive, because I imagine that people who use LatencyAware policy expect it to react reasonably fast to changes - e.g. when a node starts showing symptoms of overload.

**Comment by piodul** [comment]
> @wprzytula could you do a small r&d research and look how it's implemented in Java, and perhaps gocql?

The cpp driver might be worth looking into, too.

**Comment by wprzytula** [comment]
First conclusion: Java driver's way to latency-aware routing is similar to the solution I proposed (and that's how it came into my mind). On init, `LatencyAwarePolicy` register a `LatencyTracker` in the cluster, and it's a rather lightweight store of an [exponential moving average](http://en.wikipedia.org/wiki/Moving_average#Exponential_moving_average") (refer to `Tracker` and `HostLatencyTracker` in `LatencyAwarePolicy.java`). The `Tracker` is updated each time the query completes (successfully or with an error) by `RequestHandler`, and when a query plan is computed, each node requires a separate read from a AtomicReference (which seems to be a typical Java-devs manoeuvre...).

**Comment by wprzytula** [comment]
> I was sure I posted a response a few days ago, but maybe I didn't hit the Comment button... so let me start over:
> 
> Notifying LatencyAwarePolicy is one way, but LatencyAwarePolicy could also ask nodes for their fresh latency information right before making a decision. Then, nodes update their latency info locally when taking part in query processing, and the information is only gathered once needed - i.e. when LatencyAwarePolicy needs to make a decision. I think that this way may make sense, because it delays aggregating computation results until they're needed, and avoids keeping another bunch of atomically refcounted pointers to Node instances. Let's assume we have a token-aware latency-aware policy. Token awareness would reduce the candidates to 3 nodes, and out of these 3 nodes, the latency-aware policy will choose a subset with predicted best latency by examining the nodes' latency information right before making the choice.

But what kind of latency information do you suggest storing inside `Node` ? An exponential moving average? Last _n_ latencies?

**Comment by psarna** [comment]
If Java uses a lightweight exponential moving average, perhaps we can assume it works well enough for them and do the same. Each node could keep that information internally, it would get updated on every query, and LatencyAware policy would ask for that information and use it when deciding which replicas to pick - in particular, if it's wrapped in TokenAware policy, it would only do so for nodes that own the particular data.

**Comment by wprzytula** [comment]
How would we decide that such per-node latency information shall be collected? Type-casts with Any trait to the particular LatencyAwarePolicy seems to be a big no-no, so perhaps we could add a new method to RetryPolicy trait: `requires_latency_measurements() -> bool`, which would set up session accordingly for measuring latencies or not.

**Comment by psarna** [comment]
Sounds good to me. The alternative is to collect unconditionally (and then expose the information via metrics), but that may be a little too costly in terms of performance, and it's hard to guess without  benchmarks

**Comment by wprzytula** [comment]
As such information (whether a policy requires latency stats collection) is constant per policy, I believe it could be done better in Rust using enums. One option to do so would be to make RetryPolicy an enum of two variants: WithLatencyMeasurements and WithoutLatencyMeasurements, each containing a Box<dyn TRAIT>, where TRAIT={RetryPolicyWithLatencyMeasurements, RetryPolicyWithoutLatencyMeasurements}. Although beauty of such solution is debatable, it would make better utilization of Rust type system instead of moving responsibility to runtime checks. WDYT?

**Comment by psarna** [comment]
I'd go with a runtime check, under the assumption that most users won't be interested in latencyaware routing, so it's better to keep the code prettier for the common case. @piodul, @cvybhu?

**Comment by piodul** [comment]
I agree with @psarna.

**Comment by cvybhu** [comment]
> I'd go with a runtime check, under the assumption that most users won't be interested in latencyaware routing, so it's better to keep the code prettier for the common case. @piodul, @cvybhu?

Runtime check sounds good. What if in the future we were to introduce other metrics for nodes like error rate, requests/s etc.
We would have to exponentially many enum variants.

**Comment by cvybhu** [comment]
I guess collecting the latency of actual queries instead of network might have its own benefits. When a node becomes overloaded its latency would go up and we could limit the amount of queries it gets.
