### ISSUE TITLE
Documentation book is not searchable

### ISSUE THREAD

**Issue by cvybhu** [scylladb/scylla-rust-driver#520]
Search results on https://rust-driver.docs.scylladb.com/stable/index.html don't include docs for rust driver.

For example searching for `Default Retry Policy` gives some results, but none of them are from rust driver book: https://rust-driver.docs.scylladb.com/stable/index.html#q=default%20retry%20policy

Broken search severely limits usability of these docs.

When viewing search results on the left there are a few project listed, but rust driver isn't there, maybe it needs to be added?

Search used to work well in the old mdbook book: https://cvybhu.github.io/scyllabook/index.html?search=Default%20retry%20policy

**Comment by psarna** [comment]
you reposted the official docs link again instead of the old book - but, in any case, I think it's an issue that should be reported to scylladb/scylladb, because it's the official documentation that's broken

**Comment by cvybhu** [comment]
Oops fixed the link.

Ok, I will open an issue in `scylladb/scylladb`

**Comment by psarna** [comment]
oh wait - I just noticed **we** generate these sphinx docs in this repo. So no need to open an issue in scylladb/scylladb

**Comment by annastuchlik** [comment]
@psarna You generate the documentation in this repo, but I must be aware of any problems with the docs, so thanks @cvybhu for letting me know :)
I'm not yet sure if the problem is on our end or if it's the search that's causing it. The search mechanism is provided externally, so I've opened a ticket with the provided.

**Comment by annastuchlik** [comment]
The problem was caused by our search configuration. It has now been fixed. Here is a screenshot I've just taken, but you can verify yourself by searching for another Rust driver-related phrase.
![image](https://user-images.githubusercontent.com/37244380/185634562-a880dac6-92ae-48b4-9fbe-3ec836194c11.png)

PS. The name of the product on the selection menu will be updated later to ScyllaDB Rust Driver.

**Comment by cvybhu** [comment]
Awesome thanks, closing as fixed
