### ISSUE TITLE
Add support for custom authentication

### ISSUE THREAD

**Issue by Gor027** [scylladb/scylla-rust-driver#562]
#### Motivation:

Custom authentication is useful for integrating with more complex authentication systems like Kerberos, instead of authenticating with a username and password. This will also allow us to easily add custom authentication to the [Cpp-Rust](https://github.com/scylladb/cpp-rust-driver) driver.

#### Suggestion:

My suggestion is inspired by the implementation of custom authentication in the C++ driver and the current authentication implementation in the Rust driver:

1. Introduce an `Authenticator` trait

```Rust
use bytes::BufMut;

pub trait Authenticator: Send + Sync {
    async fn initial_response(&self, response: &mut impl BufMut) -> bool;

    async fn evaluate_challenge(&self, token: Option<Vec<u8>>, response: &mut impl BufMut) -> bool;

    async fn success(&self, token: Option<Vec<u8>>) -> bool;

    fn error() -> &str;
}
```

2. Add authenticator to `ConnectionConfig`:

```Rust
pub struct ConnectionConfig {
    /* ... */
    pub authenticator: Arc<dyn Authenticator>;
}
```
The `authenticator` should be either initialized based on the `SessionConfig`, like `ssl_context` is being set currently, or there should be a default authenticator, in my opinion, the current implementation should be the default authentication:

```Rust
struct PlainTextAuthenticator {
    username: String,
    password: String,
}

impl Authenticator for PlainTextAuthenticator {
  async fn initial_response(&self, response: &mut impl BufMut) -> bool {
      let username_as_bytes = self.username.as_ref().unwrap().as_bytes();
      let password_as_bytes = self.password.as_ref().unwrap().as_bytes();

      // The body of AuthResponse is a single [bytes] value (i32 length and then contents)
      let buf_size = 2 + username_as_bytes.len() + password_as_bytes.len();
      response.put_i32(buf_size.try_into()?);

      response.put_u8(0);
      response.put_slice(username_as_bytes);
      response.put_u8(0);
      response.put_slice(password_as_bytes);
      return true;
  }

  /* The other functions should just return true */
}
```
 
The `response: &mut impl BufMut` later can be sent by calling `Connection::send_request`.

3. The `evaluate_challenge`  and `success` should be called respectively for the `AuthChallenge` and `AuthSuccess` authentication responses. In case the functions return `false`, the `error()` function can be used to retrieve the error string.

**Comment by piodul** [comment]
One problem I see with this design is that some authenticators may want to keep some local state while the authentication process is ongoing. It might happen that multiple connections are being opened concurrently and all of them need authentication therefore we cannot have a single `Authenticator` and keep the state there. I would recommend adding another trait, e.g. `AuthenticatorSession` which has the methods of the `Authenticator` from your proposal. The actual `Authenticator` would only have a single, factory method which would be called at the beginning of the authentication process.

We already use this pattern in `LoadBalancingPolicy` and `RetryPolicy`. We also used this pattern in scylla-cdc-rust (`ConsumerFactory` + `Consumer`).

Second, it looks like you might have followed the cpp driver's interface a little too closely. I'd introduce a couple of changes to make it more "rusty":
- Instead of returning a boolean that indicates whether the function succeeded or not, you can just return `Result<Bytes, AuthenticationError>` where `AuthenticationError` can be a custom type (no need for anything more complicated than a wrapper over a `String`).
- No need to take a reference to an output argument (`response: &mut impl BufMut`), you can just return `Result<Bytes, AuthenticationError>` from the function.
- No need for the `error()` method, either.

Finally, please remember that in order to have async methods in traits you need to put `#[async_trait]` before the trait's definition. The rust language does not support async methods in traits yet, so we are using the [`async_trait`](https://docs.rs/async-trait/latest/async_trait/) crate to fake it.
