### ISSUE TITLE
Do not fetch all keyspaces

### ISSUE THREAD

**Issue by wyfo** [scylladb/scylla-rust-driver#574]
I have dozens of keyspaces with hundreds of tables in a cluster. I'm only using one keyspace for my application, but the driver still fetch all the tables/views/udt of each keyspaces, so dozens of thousands of rows. That's a lot of memory/CPU/network waste.

Moreover, I don't even use any of the metadata fetched in the `ClusterData.keyspaces`, except the keyspace strategy that the driver use itself automatically.

The driver should make metadata fetching configurable, to prevent this waste of resource.

**Comment by piodul** [comment]
You can disable fetching schema-related metadata with [`SessionBuilder::fetch_schema_metadata`](https://docs.rs/scylla/0.6.1/scylla/transport/session_builder/struct.SessionBuilder.html#method.fetch_schema_metadata). The only thing which should be fetched after disabling that flag is information about peers/tokens and keyspace replication strategies so that token-aware routing works.

Perhaps documentation related to the flag should be improved. The docstrings are quite laconic and the flag doesn't seem to be mentioned anywhere in the book.

We could also make it possible to configure for which keyspace metadata should be fetched, and maybe which parts of the metadata should be fetched (although the latter might not be that simple as some schema elements will depend on others, e.g. tables will depend on UDTs).

**Comment by wyfo** [comment]
> We could also make it possible to configure for which keyspace metadata should be fetched

In my case, I'm using some metadata because of https://docs.rs/scylla/latest/scylla/transport/struct.ClusterData.html#method.get_endpoints, so I think it would be the solution.
I've open a PR to discuss it.

**Comment by wyfo** [comment]
By the way, I wonder what's the point of having metadata fetched by the driver. I know that keyspace strategies are used for load balancing, but I think that's all. There are also no examples about metadata use. Do you know some use case? Actually, I'm not sure that other drivers offer schema introspection (didn't see it in Python driver doc).

I mean, this feature, with its default parameters, is quite an issue in my case (several MB of memory waste), and I'm start thinking that schema introspection, if useful, should be moved in a separate crate. It would simplify the driver quite a bit, and improve the memory footprint of all people like me who do not think to set `fetch_schema_metadata` to `false`.
As keyspace strategies are only used with prepared statements, they could be retrieved and cached when statement are prepared.

However, the new https://docs.rs/scylla/latest/scylla/transport/struct.ClusterData.html#method.get_endpoints uses metadata to get table partitioner. This was a mistake of mine, because I've written this function with mandatory schema fetching in mind (I didn't know it could be disabled). Now, I think I should have have use partitioner directly instead of table name (partitioner could be retrieved from database if needed).

**Comment by wyfo** [comment]
I've just realized that setting `fetch_schema_metadata` to `false` prevent prepared statements to get their partitioner, which is then defaulted to Murmur3. 

`fetch_schema_metadata` is thus not really compatible with CDC, and I think that's an issue.

**Comment by wyfo** [comment]
@ultrabug

**Comment by ultrabug** [comment]
Proposal: since the driver has the option to force its set keyspace, why couldn't we just update that keyspace when the option is used?

**Comment by piodul** [comment]
> By the way, I wonder what's the point of having metadata fetched by the driver. I know that keyspace strategies and table partitioner are used for load balancing, but I think that's all. There are also no examples about metadata use. Do you know some use case? Actually, I'm not sure that other drivers offer schema introspection (didn't see it in Python driver doc).

The Cassandra/Scylla drivers I know about (Java, Python, CPP, gocql) expose APIs for schema metadata. For example, for the Python driver you can access the schema metadata via the `metadata` field in the `Cluster` object (see [here](https://docs.datastax.com/en/developer/python-driver/3.25/api/cassandra/cluster/#cassandra.cluster.Cluster.metadata)).

> 
> I mean, this feature, with its default parameters, is quite an issue in my case (several MB of memory waste), and I'm start thinking that schema introspection, if useful, should be moved in a separate crate. It would simplify the driver quite a bit, and improve the memory footprint of all people like me who do not think to set `fetch_schema_metadata` to `false`. As keyspace strategies and table partitioner are only used with prepared statements, they could be retrieved and cached when statement are prepared.

At first, I was a bit skeptical about the idea of separating metadata completely from the driver, but after thinking about it more I realized that moving the (full) schema metadata out of the session would give the most flexibility. The session could indeed keep minimal schema metadata (keyspace replication strategy + partitioners), however this metadata would probably have to be kept updated all of the time just like the full schema metadata is now because some existing APIs may require it. One example that I know of is `get_token`, it requires information about partitioner and keyspace metadata - if it were to lazily fetch this information when called, it would have to be made async (maybe it's not too bad, but feels weird). It would still be much less than the full metadata.

If we move the schema metadata out of the Session, there should be an opt-in possibility to have the metadata maintained and regularly fetched. The reason for this is that we are [re-implementing the CPP driver using the Rust driver](https://github.com/scylladb/cpp-rust-driver/); the CPP driver maintains metadata and offers an API which allows to inspect the schema immediately and that API isn't asynchronous.

These changes are definitely more work than the `keyspaces_to_fetch` approach, but `keyspaces_to_fetch` can be a temporary solution before the full one is implemented.

**Comment by piodul** [comment]
The PR with the `keyspaces_to_fetch` configuration option was merged. I created another issue to track further refactors of metadata fetching: https://github.com/scylladb/scylla-rust-driver/issues/595
