### ISSUE TITLE
Driver panics while paging because it calls `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by Jasperav** [scylladb/scylla-rust-driver#608]
I have a flaky test and while I tried debugging the problem, I noticed the problem is inside the driver. I attached some screenshots:

Inside iterator.rs:
![image](https://user-images.githubusercontent.com/20363565/204089016-57f30e31-54ac-42c7-9f70-588e923fc557.png)

Relevant stacktrace:
![image](https://user-images.githubusercontent.com/20363565/204089043-9e6b4ef7-41e5-41b0-8b4f-2a5410825123.png)

The problem:
![image](https://user-images.githubusercontent.com/20363565/204089060-4ef38755-0cef-46d5-879a-eb2579ce1cb1.png)

I am paging in a distributed environment where rows are removed and added all the time. Maybe there are more places in this driver which calls `unwrap` while it can fail. 

I looked a bit inside the code. I don't understand this logic:

![image](https://user-images.githubusercontent.com/20363565/204089827-ae0e52ea-0d37-47d9-9d52-d1218eab583f.png)

A tokio task is spawned and right after that, we wait for the result of that task. I am not sure why the tokio task is spawn at all. I think the spawning can be removed and just await the `worker.work` result. If that is okay, the whole `work` method can be refactored by pulling out the `sender` variable and just make the method return `mpsc::Sender<Result<ReceivedPage, QueryError>>`. That is a lot safer than `unwrap` and forces returning the correct values.

**Comment by Jasperav** [comment]
@piodul I don't see that warning before the crash. I don't see any weird logging before the crash. Why is there a `sender` and `receiver` and not just a return value? It looks easier to me that `work` returns a value, rather than dealing with a `sender` and `receiver`.

**Comment by piodul** [comment]
The `execute_iter` method keeps some the state related to retries through control flow. You can see there are `nodes_in_plan` and `same_node_retries` loops. If we wanted to change the design so that RowIteratorWorker::work() just returns the next page, we would have to put this state into the RowIteratorWorker and basically reimplement the work() and query_pages() methods. I'm not sure if it would result in clearer code - personally I find `async` functions easier to reason about than manually written state machines.

Besides, I'm not sure such rework would give us any more safety. For the sake of RowIterator::get_column_specs, the driver requires that at least one page should be returned - and the new interface still wouldn't guarantee this. The first invocation of work() still can return `None`, and the unwrap problem would still be there.

I agree that it would be great for `RowIteratorWorker::work` to guarantee that it returns at least one page via the type system, but I don't have a good idea how to do it...

The idea of having a task which fetches pages in the background is so that the worker concurrently fetches the next page while the user processes the current one. This reduces latency - if processing of a page takes a lot of time, you don't have to wait as much time for the next one as it was fetched by the worker in the background.

@Jasperav are you able to reproduce this bug? If so, could you enable tracing with highest verbosity and show what the `scylla` crate outputs during the problematic query?

**Comment by Jasperav** [comment]
@piodul Note that there is another return at line 358. It returns the `fn` not the inner block. Can this also cause the `unwrap` err?

**Comment by piodul** [comment]
> @piodul Note that there is another return at line 358. It returns the `fn` not the inner block. Can this also cause the `unwrap` err?

If this return is reached, it means that `query_pages` returned Ok (line 455 or 460), and that means that `query_pages` sent something to the `sender` channel (or tried to but `receiver` was dropped).

**Comment by piodul** [comment]
I sent a PR that should fix the issue: https://github.com/scylladb/scylla-rust-driver/pull/609. Although the `unwrap()` is still there, the `RowIteratorWorker::work` is now forced by the type system to send something to the channel. Unless I missed something, the unwrap should now always succeed.

**Comment by Jasperav** [comment]
Thanks as always @piodul  :)
