### ISSUE TITLE
What about connecting to DataStax Astra?

### ISSUE THREAD

**Issue by pkolaczk** [scylladb/scylla-rust-driver#659]
The good news is that as of version 0.7 it *almost* works, albeit it is a bit manual:

1. Create an Astra DB, get the database ID, user/password and secure bundle
2. Unpack the secure bundle locally.
3. Set the user/password, enable SSL and point Scylla driver to the SSL cert, SSL key and SSL CA cert unpacked form the bundle.
4. Profit ;)

What doesn't work:
- Currently unlike the official drivers it connects only to *one* node, the initial contact point. This is because the list of nodes that the driver receives from the cluster are all private addresses.  So load balancing does not work at all. 

Instead of trying to connect to the private nodes directly, it should pass the  target node address in SSL SNI when connecting to one of the public IPs of the initial contact point. It is recommended to use all public IP addresses, for better reliability.

**Comment by dorlaor** [comment]
We have SSL+SNI option too, need to see if it can be used

**Comment by piodul** [comment]
> We have SSL+SNI option too, need to see if it can be used

Yes. We merged support for it recently (https://github.com/scylladb/scylla-rust-driver/pull/614). Unfortunately, support for specifying custom SNI when connecting to a particular node is hardcoded - specific only to Scylla Cloud sessions - so I doubt it can be useful for DataStax Astra at the moment.

We initially considered extending the driver interface to allow for custom dialers (a'la gocql: https://pkg.go.dev/github.com/gocql/gocql#Dialer) and use that to connect to Scylla Cloud clusters. I guess that such approach would also probably work for DataStax Astra. Due to time constraints we didn't use this approach, but I think it would be worthwhile to refactor the code to use this pattern at some point, as a way of reducing technical debt.

cc: @wprzytula

**Comment by avelanarius** [comment]
Closing this, since this is currently not on our roadmap, however most of the heavy lifting is already done via `cloud` feature.
