### ISSUE TITLE
DcAwareRoundRobinPolicy missing in 0.8.0

### ISSUE THREAD

**Issue by maxnachlinger** [scylladb/scylla-rust-driver#680]
Hey awesome `scylla` crate maintainers! Thanks for such a great library. I recently upgraded `scylla` from `0.7.0` to `0.8.0` and now `scylla::load_balancing::DcAwareRoundRobinPolicy` is missing. I'd be grateful for any pointers to its new whereabouts :)

**Comment by piodul** [comment]
Hi,

The load balancing policy module has undergone a major refactor. We have removed all existing load balancing policies and replaced them with a single `DefaultPolicy` which is intended to be a suitable replacement for all of them.

See the documentation page for more details: https://rust-driver.docs.scylladb.com/stable/load-balancing/default-policy.html

To create an instance of the default policy, you need to use the `DefaultPolicyBuilder`: https://docs.rs/scylla/0.8.0/scylla/transport/load_balancing/struct.DefaultPolicyBuilder.html. In order to enable dc-aware behavior, you need to specify the `preferred_datacenter` option.
