### ISSUE TITLE
changes to token aware routing?

### ISSUE THREAD

**Issue by rukai** [scylladb/scylla-rust-driver#681]
Have there been any bug fixes to token aware routing between 0.7 and 0.8?
If not there may have been a bug introduced.

I have an integration test for a project I work on that compares the token aware routing between the project itself, cdrs-tokio's token aware routing and scylla-rust-drivers token aware routing.
Since 0.8 scylla-rust-driver has diverged from the other 2 implementations:
https://github.com/shotover/shotover-proxy/pull/1099
As of 0.8, when we run this test with a cdrs-tokio connection it passes but it fails with scylla-rust-driver:
https://github.com/shotover/shotover-proxy/blob/main/shotover-proxy/tests/cassandra_int_tests/routing.rs

Its quite possible it was a bug fix rather then a bug introduced, so wanted to ask early.

**Comment by piodul** [comment]
We did a rewrite of the load balancing module but didn't intend to fix any bugs related to how replicas are chosen, so this might be a regression.

@havaker could you take a look?

**Comment by havaker** [comment]
I analyzed the failing tests and observed the following:

Tests are failing due to this line: https://github.com/scylladb/scylla-rust-driver/blob/5899fdf315fee1d25410d0c5d5648c3626080570/scylla/src/transport/load_balancing/default.rs#L566 Default policy cannot get information about the newly created test keyspace metadata, and falls back to token-unaware load balancing.

From what I saw in the `shotover-proxy`'s `cassandra_int_tests` code, on the beginning of each test, [keyspace and table is being created](https://github.com/shotover/shotover-proxy/blob/7220c131c12766ec8443b20d0f5affbccbfb1161/shotover-proxy/tests/cassandra_int_tests/routing.rs#L18-L19), then some queries are fired. For load balancing to work properly, on each schema change a new metadata must be downloaded from the cluster (to e.g. get info about replication strategy of each keyspace).

I've put a `tokio::time::sleep` after `create_keyspace` in the [`test` function](https://github.com/shotover/shotover-proxy/blob/7220c131c12766ec8443b20d0f5affbccbfb1161/shotover-proxy/tests/cassandra_int_tests/routing.rs#L17) and observed that all the tests have passed, so this seems to be an issue with metadata update timing.

What is weird is that we have a [mechanism to automatically refresh schema metadata](https://github.com/scylladb/scylla-rust-driver/blob/5899fdf315fee1d25410d0c5d5648c3626080570/scylla/src/transport/session.rs#L624) when we detect a schema change, so I'm a bit surprised that this code doesn't work in its current form.

I will try to find out more about the causes of this problem this week.

**Comment by rukai** [comment]
Thankyou for your continued investigation.
I've added the sleeps to the PR and confirmed that it does solve the problem however I'll wait for a proper fix to land upstream before merging.

**Comment by piodul** [comment]
I've put the pieces together and have an explanation.

As @havaker pointed out, the default load balancing policy will choose a random node in case information about keyspace is not available. This behavior is different from what would happen in 0.7.0 - in the old version the load balancing policy would fall back to SimpleStrategy RF=1, so it would accidentally calculate the first replica as it should because you have such a keyspace in the test.

The reason why information about keyspace is missing from the metadata is because there are actually _two_ sessions here: one that connects to proxy, and the other that connects directly to the cluster. The first one is used to create a keyspace and the table; after each statement it will notice the SchemaChange response and will pull the newest schema. However, the second session doesn't pull the schema because it doesn't do any schema-altering operations so it doesn't have information about the new keyspace.

This could be kind-of fixed if sessions reacted to schema events (they don't AFAIK), but to be fair that wouldn't be a proper fix. There is no guarantee that, by the time keyspace and table are created, all sessions will have refreshed their metadata. The metadata should be refreshed explicitly.

Adding an explicit metadata refresh in `single_key::test` fixes the problem (although it should probably also be included in other tests in that module):

```diff
diff --git a/shotover-proxy/tests/cassandra_int_tests/routing.rs b/shotover-proxy/tests/cassandra_int_tests/routing.rs
index b8fe86e2..3510f9cb 100644
--- a/shotover-proxy/tests/cassandra_int_tests/routing.rs
+++ b/shotover-proxy/tests/cassandra_int_tests/routing.rs
@@ -18,6 +18,10 @@ mod single_key {
         create_keyspace(shotover).await;
         create_table(shotover).await;
 
+        if let CassandraConnection::Scylla { ref session, .. } = &cassandra {
+            session.refresh_metadata().await.unwrap();
+        }
+
         let insert_cql =
             "INSERT INTO test_routing_ks.my_test_table_single (key, name) VALUES (?, 'my_name')";
         let prepared_insert = shotover.prepare(insert_cql).await;
```

**Comment by rukai** [comment]
Thankyou for the in depth investigation and well written explanation.
The approach we'll take to solve it on our end is to create the second connection after making the changes to the schema on the first connection. This should be robust across different driver types.

I'll go ahead and close this as the appropriate fix here does not involve scylla-rust-driver side changes.
If schema event handling is something that the scylla-rust-driver project wants then you can create a separate issue to track that.

**Comment by piodul** [comment]
@rukai Thanks. Actually, there is an issue open already: https://github.com/scylladb/scylla-rust-driver/issues/546
