### ISSUE TITLE
execute_iter() wants to own the prepared statement

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla-rust-driver#811]
Whereas `Session`'s `execute()` and `execute_paged()` methods take a `prepared: &PreparedStatement`, the method `execute_iter()` takes a different argument type: `prepared: impl Into<PreparedStatement>`.  

This difference is not explained anywhere, and as a Rust newbie I couldn't understand what it means. The problem I have is that I can't seem to reuse the same prepared statement in a loop of `execute_iter()` calls (e.g., doing many different scans using the same command), while it is possible with `execute_paged()` for example.

It seems to me that maybe this is an unintentional bug, but please forgive me if it's actually an important Rust feature that I just don't understand because I'm such a Rust newbie :-(

The code I was trying to use is something like:
```rust
           let prepared_both = session.prepare(
                    "SELECT * FROM ".to_string() + &keyspace_name + "." + &base_table
                    + "WHERE token(id) > ? AND token(id) < ?")
                .await?;
           for (start_token, end_token) in &ranges {
                let mut rows_stream = session
                    .execute_iter(&prepared_both, (start_token.unwrap(), end_token.unwrap()))
                    .await?;
                ...
           }
```

Which doesn't compile:
```
error[E0277]: the trait bound `scylla::prepared_statement::PreparedStatement: From<&scylla::prepared_statement::PreparedStatement>` is not satisfied
    --> src/main.rs:103:35
     |
103  |                     .execute_iter(&prepared_both, (start_token.unwrap(), end_token.unwrap()))
     |                      ------------ ^^^^^^^^^^^^^^ the trait `From<&scylla::prepared_statement::PreparedStatement>` is not implemented for `scylla::prepared_statement::PreparedStatement`
     |                      |
     |                      required by a bound introduced by this call
     |
     = note: required for `&scylla::prepared_statement::PreparedStatement` to implement `Into<scylla::prepared_statement::PreparedStatement>`
```

**Comment by cvybhu** [comment]
The internal reason why `execute_iter` wants to own the `PreparedStatement` is that there's a background worker which fetches the consecutive pages, and we have to give it the ownership of the statement. Rust doesn't allow us to pass a reference, because the worker is on a separate fiber, and Rust can't prove that the lifetimes are correct.

Basically it's an implementation detail, which bubbled up to the user API.

In this case, you can `.clone()` the prepared statement on every loop iteration:
```rust
let mut rows_stream = session
                    .execute_iter(prepared_both.clone(), (start_token.unwrap(), end_token.unwrap()))
                    .await?;
```

Usually cloning things is a bad idea performance wise, because it's a deep copy, but `PreparedStatement` is designed in a way which makes cloning it pretty cheap - it's a struct with a few shared pointers inside.

Here's how the struct looks like, opened by clicking the `source` button in the API documentation: https://docs.rs/scylla/0.9.0/scylla/statement/prepared_statement/struct.PreparedStatement.html

**Comment by piodul** [comment]
> `prepared: impl Into<PreparedStatement>`

This means: "prepared must be of type that implements a conversion via `Into` to `PreparedStatement` type. You can read about the `From` and `Into` traits [here](https://doc.rust-lang.org/rust-by-example/conversion/from_into.html).

I think the argument actually could just be changed to `prepared: PreparedStatement`. We don't define any conversions into the prepared statement so `impl Into` is probably useless here.

As for your issue, @cvybhu was faster than me and explained that you basically need to pass `PreparedStatement` by value and you can just `.clone()` it.

**Comment by cvybhu** [comment]
I agree that it isn't intuitive at all. We should clearly explain that `PreparedStatement` is cheap to clone somewhere in the documentation, I'm not sure if we do that :/

We could also consider changing `execute_iter` to take a reference to `PreparedStatement` (or `AsRef` to avoid breaking the API). This would be more intuitive for the users, and would shift the burden of doing the `clone()` to the function, the user doesn't have to think whether the clone is cheap or not.

We're improving the API before 1.0, maybe we could also include this.

**Comment by nyh** [comment]
@cvybhu thanks. If you know that cloning a PreparedStatement is possible cheap, could execute_iter() take a `&PreparedStatement` and clone it itself?
Yes, the user can do this clone himself (and this is what I'll do now, as a workaround) and I guess you can document this in an example, but I think it will be nicer (and no need to add instructions to the documentation) if the API of the different `execute_*` functions were the same.

**Comment by Lorak-mmk** [comment]
One possible drawback of changing the argument to `&PreparedStatement` is that it introduces unnecessary clone is some scenarios. Apart from one-off queries, which are not important, here's a function from our tests:
```
async fn execute_consistency_set_on_exec_profile(
    session: &Session,
    prepared: &PreparedStatement,
    profile: ExecutionProfileHandle,
) {
    let mut prepared = prepared.clone();
    prepared.set_execution_profile_handle(Some(profile));
    session.execute(&prepared, (1,)).await.unwrap();
    session.execute_iter(&prepared, (1,)).await.unwrap();
}
```

I can imagine similar patterns (with 1 execute, not 2) in user code.
`PreparedStatement` should be cheap to clone, so this problem probably isn't important.
I guess another solution is to implement `From<&PreparedStatement> for PreparedStatement` (why there is no impl provided by Rust like `impl<T: Clone> From<&T> for T` ?), then you could pass both ref and value and it would avoid unnecessary clone.
It would be slightly inconsistent, because argument type in `execute_iter` would be different than in `execute` / `execute_paged`, but seeing that both would accept reference to statement imo it's not a problem.

**Comment by avelanarius** [comment]
Refs https://github.com/scylladb/scylla-rust-driver/issues/475

**Comment by wprzytula** [comment]
> One possible drawback of changing the argument to &PreparedStatement is that it introduces unnecessary clone is some scenarios.

Exactly, that's why let's stick to accepting a `PreparedStatement` by move.

It is very idiomatic in Rust to take ownership of a `Clone`'able argument instead of accepting a reference to it and cloning it internally. This is both for performance (no unnecessary clones, as described by @Lorak-mmk in the example above) and as a hint issued by the function, saying: _"I do need an owned version of my argument"_.
