### ISSUE TITLE
Error when running examples/execution_profile.rs - EACH_QUORUM ConsistencyLevel is only supported for writes

### ISSUE THREAD

**Issue by nsipplswezey** [scylladb/scylla-rust-driver#835]
When running the `execution_profile` example via `SCYLLA_URI="127.0.0.1:9042" cargo run --example execution_profile` the scylla-rust-driver reports `Error message: EACH_QUORUM ConsistencyLevel is only supported for writes`

```
examples % SCYLLA_URI="127.0.0.1:9042" cargo run --example execution_profile
    Finished dev [unoptimized + debuginfo] target(s) in 0.23s
     Running `/Users/practical/OneSignal/scylla-rust-driver/target/debug/examples/execution_profile`
Connecting to 127.0.0.1:9042 ...
Error: Database returned an error: The query is syntactically correct but invalid, Error message: EACH_QUORUM ConsistencyLevel is only supported for writes
```

It's unclear to me if this error is actually intentional, to demonstrate a query that fails with one profile, but succeeds in another? In which case some clarifying comments might help.

If that's not the case, I wonder if small fix changing consistency from `Consistency::EachQuorum` to `Consistency::Quorum` or `Consistency::LocalQuorum` in the `execution_profile` example would be useful.

**Comment by cvybhu** [comment]
Thanks for the report.
I can confirm that it fails, both on the latest versions of Scylla and on the old `Scylla 4.6`.

The example was added in https://github.com/scylladb/scylla-rust-driver/pull/592.
I guess it didn't work back then as well, it must've slipped by the review.
I don't think it's intentional, examples should work.

> If that's not the case, I wonder if small fix changing consistency from Consistency::EachQuorum to Consistency::Quorum or Consistency::LocalQuorum in the execution_profile example would be useful.

That's a good idea. `LocalQuorum` would be a good replacement because `Quorum` is the default value, and the example demonstrates how to override the deafults.

**Comment by cvybhu** [comment]
Opened a PR with the fix: https://github.com/scylladb/scylla-rust-driver/pull/840

**Comment by nsipplswezey** [comment]
Awesome!
