### ISSUE TITLE
FromRow is not working for type wrapper 

### ISSUE THREAD

**Issue by DylanVerstraete** [scylladb/scylla-rust-driver#852]
I have this custom type wrapper for uuid:

```
#[derive(Debug, Clone, FromRow)]
pub struct FileId(Uuid);
```
And I am getting error: `derive(FromRow) works only for structs with named fields`

Is there a reason that this does not work or is there a workaround?

**Comment by piodul** [comment]
> Is there a reason that this does not work or is there a workaround?

I'm not entirely sure why we chose to support named structs instead of tuple structs for FromRow, especially that this trait doesn't do anything with the Rust struct field names. I suppose it's a good idea to add support for it to the driver.

As a workaround, you can implement the `FromRow` trait yourself - if your tuple struct is short enough (up to 16 fields) then it's just the matter of delegating the implementation to a regular tuple, for example:

```rust
use scylla::cql_to_rust::FromRowError;
use scylla::FromRow;
use scylla_cql::frame::response::result::Row;

struct MyTupleStruct(i32, String, i64);
impl FromRow for MyTupleStruct {
    fn from_row(row: Row) -> Result<Self, FromRowError> {
        let (a, b, c) = <_ as FromRow>::from_row(row)?;
        Ok(Self(a, b, c))
    }
}
```

**Comment by DylanVerstraete** [comment]
Awesome! Thanks
